version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 774305614505.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t bank-ai .
      - docker tag bank-ai:latest 774305614505.dkr.ecr.ap-south-1.amazonaws.com/bank-ai:latest
  post_build:
    commands:
      - docker push 774305614505.dkr.ecr.ap-south-1.amazonaws.com/bank-ai:latest
      - echo Writing image definitions file...
      - printf '[{"name":"bank-ai","imageUri":"%s"}]' 774305614505.dkr.ecr.ap-south-1.amazonaws.com/bank-ai:latest > imagedefinitions.json   
artifacts:
  files: imagedefinitions.json
